### ISSUE TITLE
Update sRNAtoolbox article

### ISSUE THREAD

**Issue by sert23** [Glogobyte/isomiR_tools#1]
Hi there, nice resource.

Could you please update your list to contain the most recent version of sRNAtoolbox/sRNAbench article? 

https://academic.oup.com/nar/article/47/W1/W530/5494756

Also, I'd suggest you add Genome-free/Reference-free miRNA discovery and profiling as part of the feature description for miRNAgFree.

Thanks

**Comment by vebaev** [comment]
I updated sRNAtoolbox/sRNAbench article URL :)

**Comment by sert23** [comment]
thanks!
just for the purpose of completeness/accuracy:
sRNAtoolbox no longer supports "Visualization of sRNA expression data in a genome context using jBrowse"
sRNAbench (and many sRNAtoolbox tools) also have a stand-alone/dockerized version available. I would actually recommend sRNAbench has its own row since it has many features not described in your table such as prediction of new miRNAs.

**Comment by vebaev** [comment]
Maybe you can propose an edit to the table in Gitgub so the owner can approve? And add the features you suggest are missing? Its true we did not probably list all available features as the tool number was a lot to cover :)

**Comment by vebaev** [comment]
@sert23 we are currently making a revision of a review about plant smallRNA tools, can you edit of your convenience the following regarding sRNAbench/sRNAtoolbox so we can input the best description:

•	**Features**: miRNA identification; isomiR identification; miRNA quantification. 
•	**Third party tools and DB**: miRbase, miRGeneDB, Deseq2 and UpsetR.
•	**Output**: interactive heatmaps, box-plots , volcano-plots, genome mapping visualization, consensus tables and graphical representation of differential expression.

**Comment by sert23** [comment]
Hi @vebaev, regarding plants, I think sRNAbench has some recent improvements that could be interesting (not published yet though).
**Features**: 
- miRNA, isomiR and sncRNA identification and quantification in more than 90 species from EnsemblePlants 51, PmiREN2.0 and RNAcentral (release 20).
- prediction of de novo miRNAs.
- mapping to bacterial and viral genomes (including plant virus).
- differential expression with DESeq, DESeq2, edgeR, NOISeq and Student's t-test.

**Third party tools and DBs**: PmiREN, miRbase, miRGeneDB, RNAcentral, Deseq2, edgeR and UpsetR.
**Output**: interactive heatmaps, box-plots , volcano-plots, genome mapping visualization, consensus tables and graphical representation of differential expression.

If you want to include something more general in the list (i.e. also for animals), it could go like this:
**Features**: 
- miRNA and isomiR identification and quantification using 358 different complement annotations from MirGeneDB, miRBase and PmiREN.
- sncRNA profiling for 441 Ensembl species (release 104 and Ensembl Genomes 51) plus RNAcentral (release 20).
- mapping to bacterial and viral genomes (over 19,000 genomes) to reveal contaminants and pathogen-host interactions.
- differential expression with DESeq, DESeq2, edgeR, NOISeq and Student's t-test.

**Third party tools and DBs**: PmiREN, miRbase, miRGeneDB, RNAcentral, Deseq2, edgeR and UpsetR.
**Output**: interactive heatmaps, box-plots , volcano-plots, genome mapping visualization, consensus tables and graphical representation of differential expression.

thanks for giving us a chance to edit!

**Comment by sert23** [comment]
and other features I forgot!

- data import from SRA, Google Drive and Dropbox
- preprocessing for the most common library preparation protocols

**Comment by vebaev** [comment]
Thanks :) we have limited space as we are reviewing lot of tools,  so I will take some of your valuable input.

**Comment by sert23** [comment]
yeah, I can imagine. Here's a database summary with more information or feel free to contact us for more info :)
[https://arn.ugr.es/srnatoolbox/database](https://arn.ugr.es/srnatoolbox/database)
thanks!

**Comment by vebaev** [comment]
Thanks, so the tool also can identify vsiRNA?

**Comment by sert23** [comment]
as long as they map to a viral genome (we have one sequence per species hosted in NCBI) it should map the reads. sRNAbench will identify those as reads as belonging to the right virus (with genomic coordinates) but the tool "doesn't know" if it's a vsiRNA or not.

You can always provide your own annotation if you have a collection of vsiRNA sequences and then they'd be identified as such.
